In [ ]:
#Question 1
#Write a Python program to convert an array to an ordinary list with the same items.
#we can use the np.tolist() function
import numpy as np
a = np.array([(1, 2), (3, 4), (5,6)])
b=a.tolist()
print(b)

[[1, 2], [3, 4], [5, 6]]


In [ ]:
#Question 2 
#Write a NumPy program to compute the sum of the diagonal elements of a given array.
#Hint: Two methods to solve this problem: 1. manually(without direct function). 2. using the trace function

#méthode1
import numpy as np
a = np.array([(1, 2,5), (3, 4,7), (5,6,1)])
b=a.shape
nb_chiffres=b[0]
s=0
for i in range(0,nb_chiffres):
  s=s+a[i,i]
print(s)

6


In [ ]:
#methode2
import numpy as np 
m = 0
array = np.array([(1, 2,5), (3, 4,7), (5,6,1)])
m=np.trace(array)
print(m)

6


In [ ]:
#Question 3
#Given an array of your choice, get all the values higher than X :
#if a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2. 
def get_numbers_higher(np_array,minimum_number):
  number_list=np_array.flatten()
  for i in number_list:
    if i > minimum_number:
      print(i)

#main program
a =np.array([[1,2],[3,5]])
get_numbers_higher(a,2)




3
5


In [ ]:
#Question 4
#Given two arrays A&B having the same shape. 
#The task is to apply addition by hand: C is the new array. 
#method1:not by hand
import numpy as np 
A=np.array([[1,2],[3,5]])
B=np.array([[5,8],[1,4]])
C=A+B
D=C.tolist()
print(C)
print(D)

[[ 6 10]
 [ 4  9]]
[[6, 10], [4, 9]]


In [ ]:
#mathod2:by hand
import numpy as np
def array_sum(A,B):
  C=A.shape
  Af=A.flatten()
  Bf=B.flatten()
  sum=lambda A,B : A+B
  x=sum(Af,Bf)
  y=x.reshape(C)
  return y

#main program
A=np.array([[1,2,2],[3,5,4]])
B=np.array([[5,8,1],[1,4,3]])
C=array_sum(A,B)
print(C)

[[ 6 10  3]
 [ 4  9  7]]


In [76]:
#Question 5
#Write a NumPy program to subtract the mean of each row of a given matrix.
#Hint: use the mean function
A=np.array([[1,2,2],[3,5,4]])
b=A
i=0
j=0
for line in A:
  j=0
  line_mean=line.mean()
  for number in line:
    new_number=number-line_mean
    print(new_number)
    b[i,j]=new_number
    j=j+1
  i=i+1
print(b)

-0.6666666666666667
0.33333333333333326
0.33333333333333326
-1.0
1.0
0.0
[[ 0  0  0]
 [-1  1  0]]
